// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6QwjzFQiyWQCoKBP5MerQY2gGWtOYmWA',
    appId: '1:506328580003:web:87c6a1a1ba808ef9eda416',
    messagingSenderId: '506328580003',
    projectId: 'test6-57f45',
    authDomain: 'test6-57f45.firebaseapp.com',
    storageBucket: 'test6-57f45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeiql4Fb4kDEfnYQicF7eKWf879fHqT5g',
    appId: '1:506328580003:android:ec6ce5783fc32f3beda416',
    messagingSenderId: '506328580003',
    projectId: 'test6-57f45',
    storageBucket: 'test6-57f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANljT_cYqc38iPGbdaZSLb0MxDY0jbMp8',
    appId: '1:506328580003:ios:b0daeb9515f55202eda416',
    messagingSenderId: '506328580003',
    projectId: 'test6-57f45',
    storageBucket: 'test6-57f45.appspot.com',
    iosBundleId: 'com.example.test6',
  );
}
